micronaut:
  application:
    name: httpservicemn
  server:
    port: 8080
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
datasources:
  default:
    url: jdbc:mysql://localhost:3306/webhooks
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: password
    auto-commit: false
kafka.bootstrap.servers: localhost:9092