micronaut:
  application:
    name: httpservicemn
  server:
    port: 8080
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    binders:
      kafka:
        enabled: false
endpoints.prometheus.sensitive: false
kafka.bootstrap.servers: localhost:9092
vertx:
  mysql:
    client:
      port: 3306
      host: localhost
      database: webhooks
      user: root
      password: password
      maxSize: 5
      cache-prepared-statements: true
